# Generated by Django 3.1.7 on 2021-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210405_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetlike',
            name='tweet',
        ),
        migrations.AddField(
            model_name='tweetlike',
            name='tweet',
            field=models.ManyToManyField(to='base.Tweet'),
        ),
    ]
