# Generated by Django 3.1.7 on 2021-04-06 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_auto_20210406_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follow_user',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
